In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv('../datasets/ecommerce_customer_analytics.csv')

In [3]:
date.head()

,customer_id,age,gender,country,region,income_bracket,signup_date,last_purchase_date,customer_lifetime_days,days_since_last_purchase,...,device_type,loyalty_tier,discount_usage_rate,return_rate,newsletter_subscribed,referral_source,avg_session_duration_min,avg_pages_per_session,satisfaction_score,churn
0,CUST-00001,35,Male,United States,North America,"$75,000–$99,999",2022-10-17,2024-11-13,759,48,...,Desktop,Platinum,0.229,0.084,False,Social Media,10.2,6.4,4,0
1,CUST-00002,58,Male,Germany,Europe,"$25,000–$49,999",2020-12-05,2024-04-24,1237,251,...,Mobile,Gold,0.349,0.019,True,Social Media,1.0,6.9,5,0
2,CUST-00003,43,Female,Australia,Asia-Pacific,"$75,000–$99,999",2019-05-27,2022-10-25,1248,798,...,Desktop,Platinum,0.186,0.117,True,Paid Ad,7.4,1.1,3,1
3,CUST-00004,54,Male,United Kingdom,Europe,"$25,000–$49,999",2022-02-23,2023-08-15,539,504,...,Mobile,Gold,0.048,0.130,True,Referral,14.4,5.8,5,1
4,CUST-00005,30,Male,Brazil,Latin America,"Under $25,000",2021-06-09,2022-04-28,324,978,...,Mobile,Bronze,0.056,0.085,True,Email Campaign,5.7,4.3,5,1

In [4]:
type(date)

pandas.core.frame.DataFrame

In [5]:
date = date[['signup_date','region','country']]

In [6]:
date.head()

  signup_date         region         country
0  2022-10-17  North America   United States
1  2020-12-05         Europe         Germany
2  2019-05-27   Asia-Pacific       Australia
3  2022-02-23         Europe  United Kingdom
4  2021-06-09  Latin America          Brazil

In [7]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   signup_date  1200 non-null   object
 1   region       1200 non-null   object
 2   country      1200 non-null   object
dtypes: object(3)
memory usage: 28.3+ KB

In [8]:
date['signup_date'] = pd.to_datetime(date['signup_date'])

In [9]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   signup_date  1200 non-null   datetime64[ns]
 1   region       1200 non-null   object
 2   country      1200 non-null   object
dtypes: datetime64[ns](1), object(2)
memory usage: 28.3+ KB

In [10]:
date['year'] = date['signup_date'].dt.year
date['month'] = date['signup_date'].dt.month
date['day'] = date['signup_date'].dt.day
date['month_name'] = date['signup_date'].dt.month_name()
date['day_name'] = date['signup_date'].dt.day_name()
date['day_of_week'] = date['signup_date'].dt.day_of_week

In [11]:
date

,signup_date,region,country,year,month,day,month_name,day_name,day_of_week
0,2022-10-17,North America,United States,2022,10,17,October,Monday,0
1,2020-12-05,Europe,Germany,2020,12,5,December,Saturday,5
2,2019-05-27,Asia-Pacific,Australia,2019,5,27,May,Monday,0
3,2022-02-23,Europe,United Kingdom,2022,2,23,February,Wednesday,2
4,2021-06-09,Latin America,Brazil,2021,6,9,June,Wednesday,2
...,...,...,...,...,...,...,...,...,...
1195,2022-11-10,North America,United States,2022,11,10,November,Thursday,3
1196,2023-03-22,Europe,France,2023,3,22,March,Wednesday,2
1197,2023-01-25,North America,United States,2023,1,25,January,Wednesday,2
1198,2021-04-29,Asia-Pacific,Japan,2021,4,29,April,Thursday,3
1199,2020-03-02,Europe,United Kingdom,2020,3,2,March,Monday,0

In [12]:
date['day_is_a_weekend'] = np.where(date['day_name'].isin(['Saturday','Sunday']),1,0)

In [13]:
date.sample(5)

,signup_date,region,country,year,month,day,month_name,day_name,day_of_week,day_is_a_weekend
531,2023-07-21,North America,United States,2023,7,21,July,Friday,4,0
792,2022-10-22,Europe,Netherlands,2022,10,22,October,Saturday,5,1
1001,2020-10-02,Europe,France,2020,10,2,October,Friday,4,0
694,2022-09-27,North America,United States,2022,9,27,September,Tuesday,1,0
262,2019-09-16,Asia-Pacific,Australia,2019,9,16,September,Monday,0,0

In [14]:
date['day_is_a_weekday'] = np.where(date['day_name'].isin(['Monday','Tuesday','Wednesday','Thursday','Friday']),1,0)

In [15]:
date.sample(5)

,signup_date,region,country,year,month,day,month_name,day_name,day_of_week,day_is_a_weekend,day_is_a_weekday
1107,2023-04-24,Europe,Spain,2023,4,24,April,Monday,0,0,1
367,2023-11-27,North America,United States,2023,11,27,November,Monday,0,0,1
385,2020-10-06,Europe,Italy,2020,10,6,October,Tuesday,1,0,1
1095,2020-09-21,Europe,Germany,2020,9,21,September,Monday,0,0,1
961,2019-04-21,Europe,United Kingdom,2019,4,21,April,Sunday,6,1,0

In [16]:
date['quarter'] = date['signup_date'].dt.quarter

In [17]:
date['quarter'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1200 entries, 0 to 1199
Series name: quarter
Non-Null Count  Dtype
--------------  -----
1200 non-null   int32
dtypes: int32(1)
memory usage: 4.8 KB

In [18]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)

In [19]:
date

,signup_date,region,country,year,month,day,month_name,day_name,day_of_week,day_is_a_weekend,day_is_a_weekday,quarter,semester
0,2022-10-17,North America,United States,2022,10,17,October,Monday,0,0,1,4,2
1,2020-12-05,Europe,Germany,2020,12,5,December,Saturday,5,1,0,4,2
2,2019-05-27,Asia-Pacific,Australia,2019,5,27,May,Monday,0,0,1,2,1
3,2022-02-23,Europe,United Kingdom,2022,2,23,February,Wednesday,2,0,1,1,1
4,2021-06-09,Latin America,Brazil,2021,6,9,June,Wednesday,2,0,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2022-11-10,North America,United States,2022,11,10,November,Thursday,3,0,1,4,2
1196,2023-03-22,Europe,France,2023,3,22,March,Wednesday,2,0,1,1,1
1197,2023-01-25,North America,United States,2023,1,25,January,Wednesday,2,0,1,1,1
1198,2021-04-29,Asia-Pacific,Japan,2021,4,29,April,Thursday,3,0,1,2,1
1199,2020-03-02,Europe,United Kingdom,2020,3,2,March,Monday,0,0,1,1,1

In [20]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 8, 1, 4, 17, 5794)

In [21]:
today - date['signup_date']

0      1330 days 01:04:17.005794
1      2011 days 01:04:17.005794
2      2569 days 01:04:17.005794
3      1566 days 01:04:17.005794
4      1825 days 01:04:17.005794
                  ...
1195   1306 days 01:04:17.005794
1196   1174 days 01:04:17.005794
1197   1230 days 01:04:17.005794
1198   1866 days 01:04:17.005794
1199   2289 days 01:04:17.005794
Name: signup_date, Length: 1200, dtype: timedelta64[ns]

In [22]:
(today - date['signup_date']).dt.seconds

0       3857
1       3857
2       3857
3       3857
4       3857
        ...
1195    3857
1196    3857
1197    3857
1198    3857
1199    3857
Name: signup_date, Length: 1200, dtype: int32

In [23]:
(today - date['signup_date']).dt.days

0       1330
1       2011
2       2569
3       1566
4       1825
        ...
1195    1306
1196    1174
1197    1230
1198    1866
1199    2289
Name: signup_date, Length: 1200, dtype: int64

In [24]:
((today - date['signup_date'])/np.timedelta64(30,'D'),0)
#This takes 30 days as reference and counts months, but less accurate as months can be of 28,30,31 days. But not a big issue as 30*12=360 close to 365.
#np.round rounds off number to (number,decimals) no. of decimals we choose to. Here 0 therefore no decimal values.

(0       44.334821
 1       67.034821
 2       85.634821
 3       52.201488
 4       60.834821
           ...
 1195    43.534821
 1196    39.134821
 1197    41.001488
 1198    62.201488
 1199    76.301488
 Name: signup_date, Length: 1200, dtype: float64,
 0)

In [25]:
time = pd.read_csv('../datasets/flights.csv')

In [26]:
time.head().T

,0,1,2,3,4
id,0,1,2,3,4
year,2013,2013,2013,2013,2013
month,1,1,1,1,1
day,1,1,1,1,1
dep_time,517.0,533.0,542.0,544.0,554.0
sched_dep_time,515,529,540,545,600
dep_delay,2.0,4.0,2.0,-1.0,-6.0
arr_time,830.0,850.0,923.0,1004.0,812.0
sched_arr_time,819,830,850,1022,837
arr_delay,11.0,20.0,33.0,-18.0,-25.0
carrier,UA,UA,AA,B6,DL
flight,1545,1714,1141,725,461
tailnum,N14228,N24211,N619AA,N804JB,N668DN
origin,EWR,LGA,JFK,JFK,LGA
dest,IAH,IAH,MIA,BQN,ATL
air_time,227.0,227.0,160.0,183.0,116.0
distance,1400,1416,1089,1576,762
hour,5,5,5,5,6
minute,15,29,40,45,0
time_hour,2013-01-01 05:00:00,2013-01-01 05:00:00,2013-01-01 05:00:00,2013-01-01 05:00:00,2013-01-01 06:00:00
name,United Air Lines Inc.,United Air Lines Inc.,American Airlines Inc.,JetBlue Airways,Delta Air Lines Inc.

In [27]:
time = time[['time_hour','name','tailnum'] ]

In [28]:
time

                  time_hour                    name tailnum
0       2013-01-01 05:00:00   United Air Lines Inc.  N14228
1       2013-01-01 05:00:00   United Air Lines Inc.  N24211
2       2013-01-01 05:00:00  American Airlines Inc.  N619AA
3       2013-01-01 05:00:00         JetBlue Airways  N804JB
4       2013-01-01 06:00:00    Delta Air Lines Inc.  N668DN
...                     ...                     ...     ...
336771  2013-09-30 14:00:00       Endeavor Air Inc.     NaN
336772  2013-09-30 22:00:00       Endeavor Air Inc.     NaN
336773  2013-09-30 12:00:00               Envoy Air  N535MQ
336774  2013-09-30 11:00:00               Envoy Air  N511MQ
336775  2013-09-30 08:00:00               Envoy Air  N839MQ

[336776 rows x 3 columns]

In [30]:
time['time_hour'] = pd.to_datetime(time['time_hour'])

In [31]:
time['time'] = time['time_hour'].dt.time

In [32]:
time['time']

0         05:00:00
1         05:00:00
2         05:00:00
3         05:00:00
4         06:00:00
            ...
336771    14:00:00
336772    22:00:00
336773    12:00:00
336774    11:00:00
336775    08:00:00
Name: time, Length: 336776, dtype: object

In [36]:
hour = time['time_hour'].dt.hour
minute = time['time_hour'].dt.minute

In [59]:
hour.sample(5)

10501      7
246223    11
267031    16
137425     8
227985     9
Name: time_hour, dtype: int32

In [60]:
time.head()

            time_hour                    name tailnum      time
0 2013-01-01 05:00:00   United Air Lines Inc.  N14228  05:00:00
1 2013-01-01 05:00:00   United Air Lines Inc.  N24211  05:00:00
2 2013-01-01 05:00:00  American Airlines Inc.  N619AA  05:00:00
3 2013-01-01 05:00:00         JetBlue Airways  N804JB  05:00:00
4 2013-01-01 06:00:00    Delta Air Lines Inc.  N668DN  06:00:00

In [61]:
today - time['time_hour']

0        4905 days 20:04:17.005794
1        4905 days 20:04:17.005794
2        4905 days 20:04:17.005794
3        4905 days 20:04:17.005794
4        4905 days 19:04:17.005794
                    ...
336771   4633 days 11:04:17.005794
336772   4633 days 03:04:17.005794
336773   4633 days 13:04:17.005794
336774   4633 days 14:04:17.005794
336775   4633 days 17:04:17.005794
Name: time_hour, Length: 336776, dtype: timedelta64[ns]

In [ ]:
(today - time['time_hour'])/np.timedelta64(1,'h')
#This would give the time difference in hours

0         117740.07139
1         117740.07139
2         117740.07139
3         117740.07139
4         117739.07139
              ...
336771    111203.07139
336772    111195.07139
336773    111205.07139
336774    111206.07139
336775    111209.07139
Name: time_hour, Length: 336776, dtype: float64